spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://coredb:3306/coredb
    username: root
    password: kkaddak208!

  redis:
    host: localhost
    port: 6379
    password: kkaddak208!
